### ISSUE TITLE
the mAP on cifar10 is only 0.30

### ISSUE THREAD

**Issue by chenshen03** [thuml/HashNet#28]
For CIFAR-10, I randomly select 100 images per class as the test query set, and 500 images per class as the training set. The remaining images serve as database set.

I trained HashNet with command as follow:
`python -u train.py --gpu_id 0 --dataset cifar --prefix resnet50_hashnet --hash_bit 48 --net ResNet50 --lr 0.0003 --class_num 1.0
`

The final mAP is only 0.302986.

**Comment by dweiiiiiiiiii** [comment]
你好，请问你也只是在cifar-10上得到的结果不太好而在其他数据集上结果正常吗？

**Comment by chenshen03** [comment]
@dweiiiiiiiiii 是的，应该和你结果差不多。

**Comment by chenshen03** [comment]
@caozhangjie Can you explain why HashNet behaves so badly on CIFAR10?

**Comment by caozhangjie** [comment]
Cifar 10 has 10 classes, I recommend replace the class_num to 10. Also, Cifar 10 needs a different backbone network. Please search for a proper backbone.

**Comment by zhouxiaohang** [comment]
> Cifar 10 has 10 classes, I recommend replace the class_num to 10. Also, Cifar 10 needs a different backbone network. Please search for a proper backbone.

Since CIFAR 10 with 10 classes needs class_num to be 10, why COCO dataset with 80 classes is compatible with class_num=1.0? I've tried (64 bits are used.):

COCO dataset with class_num=80.0, mAP=0.53
COCO dataset with class_num=1.0, mAP=0.80 (which is higher than that in paper)

How to explain this?
